#define DEFUSAL_IDD 310721
#define DEFUSAL_RED_IDD DEFUSAL_IDD + 1
#define DEFUSAL_GREEN_IDD DEFUSAL_IDD + 2
#define DEFUSAL_BLUE_IDD DEFUSAL_IDD + 3
#define DEFUSAL_YELLOW_IDD DEFUSAL_IDD + 4
#define DEFUSAL_MAGENTA_IDD DEFUSAL_IDD + 5
#define DEFUSAL_ORANGE_IDD DEFUSAL_IDD + 6
#define DEFUSAL_GRAY_IDD DEFUSAL_IDD + 7
#define DEFUSAL_EXAMPLE_EXPLOSION_IDD DEFUSAL_IDD + 1337
#define WIRE_WIDTH 0.1
#define WIRE_HEIGHT 0.8
#define WIRE_BORDER 0.05
#define WIRE_GAP 0.01
